//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABotSupport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public decimal UpdateDelay {
            get {
                return ((decimal)(this["UpdateDelay"]));
            }
            set {
                this["UpdateDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseLinearRegression {
            get {
                return ((bool)(this["UseLinearRegression"]));
            }
            set {
                this["UseLinearRegression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public decimal HPLimit1 {
            get {
                return ((decimal)(this["HPLimit1"]));
            }
            set {
                this["HPLimit1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color HPColor1 {
            get {
                return ((global::System.Drawing.Color)(this["HPColor1"]));
            }
            set {
                this["HPColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal HPLimit2 {
            get {
                return ((decimal)(this["HPLimit2"]));
            }
            set {
                this["HPLimit2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color HPColor2 {
            get {
                return ((global::System.Drawing.Color)(this["HPColor2"]));
            }
            set {
                this["HPColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public decimal MPLimit1 {
            get {
                return ((decimal)(this["MPLimit1"]));
            }
            set {
                this["MPLimit1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color MPColor1 {
            get {
                return ((global::System.Drawing.Color)(this["MPColor1"]));
            }
            set {
                this["MPColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal MPLimit2 {
            get {
                return ((decimal)(this["MPLimit2"]));
            }
            set {
                this["MPLimit2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color MPColor2 {
            get {
                return ((global::System.Drawing.Color)(this["MPColor2"]));
            }
            set {
                this["MPColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal CharismaLimit1 {
            get {
                return ((decimal)(this["CharismaLimit1"]));
            }
            set {
                this["CharismaLimit1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color CharismaColor1 {
            get {
                return ((global::System.Drawing.Color)(this["CharismaColor1"]));
            }
            set {
                this["CharismaColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal CharismaLimit2 {
            get {
                return ((decimal)(this["CharismaLimit2"]));
            }
            set {
                this["CharismaLimit2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color CharismaColor2 {
            get {
                return ((global::System.Drawing.Color)(this["CharismaColor2"]));
            }
            set {
                this["CharismaColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79")]
        public decimal DurabilityLimit1 {
            get {
                return ((decimal)(this["DurabilityLimit1"]));
            }
            set {
                this["DurabilityLimit1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color DurabilityColor1 {
            get {
                return ((global::System.Drawing.Color)(this["DurabilityColor1"]));
            }
            set {
                this["DurabilityColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public decimal DurabilityLimit2 {
            get {
                return ((decimal)(this["DurabilityLimit2"]));
            }
            set {
                this["DurabilityLimit2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color DurabilityColor2 {
            get {
                return ((global::System.Drawing.Color)(this["DurabilityColor2"]));
            }
            set {
                this["DurabilityColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CopyItemNameOnClick {
            get {
                return ((bool)(this["CopyItemNameOnClick"]));
            }
            set {
                this["CopyItemNameOnClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public decimal LoyaltyLimit1 {
            get {
                return ((decimal)(this["LoyaltyLimit1"]));
            }
            set {
                this["LoyaltyLimit1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public global::System.Drawing.Color LoyaltyColor1 {
            get {
                return ((global::System.Drawing.Color)(this["LoyaltyColor1"]));
            }
            set {
                this["LoyaltyColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("59")]
        public decimal LoyaltyLimit2 {
            get {
                return ((decimal)(this["LoyaltyLimit2"]));
            }
            set {
                this["LoyaltyLimit2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color LoyaltyColor2 {
            get {
                return ((global::System.Drawing.Color)(this["LoyaltyColor2"]));
            }
            set {
                this["LoyaltyColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public decimal PredictLevel {
            get {
                return ((decimal)(this["PredictLevel"]));
            }
            set {
                this["PredictLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCopyPetScreenshotMenuItem {
            get {
                return ((bool)(this["DisplayCopyPetScreenshotMenuItem"]));
            }
            set {
                this["DisplayCopyPetScreenshotMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplaySavePetScreenshotMenuItem {
            get {
                return ((bool)(this["DisplaySavePetScreenshotMenuItem"]));
            }
            set {
                this["DisplaySavePetScreenshotMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCopyCurrentStatsMenuItem {
            get {
                return ((bool)(this["DisplayCopyCurrentStatsMenuItem"]));
            }
            set {
                this["DisplayCopyCurrentStatsMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCopyBaseStatsMenuItem {
            get {
                return ((bool)(this["DisplayCopyBaseStatsMenuItem"]));
            }
            set {
                this["DisplayCopyBaseStatsMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCopyAllPetStatsMenuItem {
            get {
                return ((bool)(this["DisplayCopyAllPetStatsMenuItem"]));
            }
            set {
                this["DisplayCopyAllPetStatsMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayPredictStats {
            get {
                return ((bool)(this["DisplayPredictStats"]));
            }
            set {
                this["DisplayPredictStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayBaseStats {
            get {
                return ((bool)(this["DisplayBaseStats"]));
            }
            set {
                this["DisplayBaseStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableMapList {
            get {
                return ((bool)(this["DisableMapList"]));
            }
            set {
                this["DisableMapList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseMapListAsWhitelist {
            get {
                return ((bool)(this["UseMapListAsWhitelist"]));
            }
            set {
                this["UseMapListAsWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDifferentialCopyBasedOnClickTarget {
            get {
                return ((bool)(this["EnableDifferentialCopyBasedOnClickTarget"]));
            }
            set {
                this["EnableDifferentialCopyBasedOnClickTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoRemoveWhitespace {
            get {
                return ((bool)(this["AutoRemoveWhitespace"]));
            }
            set {
                this["AutoRemoveWhitespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCopyPredictStatsMenuItem {
            get {
                return ((bool)(this["DisplayCopyPredictStatsMenuItem"]));
            }
            set {
                this["DisplayCopyPredictStatsMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyPetStatsOnRightClick {
            get {
                return ((bool)(this["CopyPetStatsOnRightClick"]));
            }
            set {
                this["CopyPetStatsOnRightClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTeamChannel {
            get {
                return ((bool)(this["ShowTeamChannel"]));
            }
            set {
                this["ShowTeamChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPrivateChannel {
            get {
                return ((bool)(this["ShowPrivateChannel"]));
            }
            set {
                this["ShowPrivateChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFamilyChannel {
            get {
                return ((bool)(this["ShowFamilyChannel"]));
            }
            set {
                this["ShowFamilyChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAnnounceChannel {
            get {
                return ((bool)(this["ShowAnnounceChannel"]));
            }
            set {
                this["ShowAnnounceChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowJobChannel {
            get {
                return ((bool)(this["ShowJobChannel"]));
            }
            set {
                this["ShowJobChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWorldChannel {
            get {
                return ((bool)(this["ShowWorldChannel"]));
            }
            set {
                this["ShowWorldChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInterworldChannel {
            get {
                return ((bool)(this["ShowInterworldChannel"]));
            }
            set {
                this["ShowInterworldChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMergedChatMode {
            get {
                return ((bool)(this["EnableMergedChatMode"]));
            }
            set {
                this["EnableMergedChatMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBroadcastChannel {
            get {
                return ((bool)(this["ShowBroadcastChannel"]));
            }
            set {
                this["ShowBroadcastChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSystemChannel {
            get {
                return ((bool)(this["ShowSystemChannel"]));
            }
            set {
                this["ShowSystemChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCopyBoostStatsMenuItem {
            get {
                return ((bool)(this["DisplayCopyBoostStatsMenuItem"]));
            }
            set {
                this["DisplayCopyBoostStatsMenuItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public decimal BoostLevel {
            get {
                return ((decimal)(this["BoostLevel"]));
            }
            set {
                this["BoostLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AssumeBoostKingPet {
            get {
                return ((bool)(this["AssumeBoostKingPet"]));
            }
            set {
                this["AssumeBoostKingPet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayBoostStats {
            get {
                return ((bool)(this["DisplayBoostStats"]));
            }
            set {
                this["DisplayBoostStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAccountPasswords {
            get {
                return ((bool)(this["SaveAccountPasswords"]));
            }
            set {
                this["SaveAccountPasswords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountPasswordCollection {
            get {
                return ((string)(this["AccountPasswordCollection"]));
            }
            set {
                this["AccountPasswordCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssaPathCollection {
            get {
                return ((string)(this["AssaPathCollection"]));
            }
            set {
                this["AssaPathCollection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerlistINIPath {
            get {
                return ((string)(this["ServerlistINIPath"]));
            }
            set {
                this["ServerlistINIPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHideOnLogin {
            get {
                return ((bool)(this["AutoHideOnLogin"]));
            }
            set {
                this["AutoHideOnLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDetermineBoostKingPet {
            get {
                return ((bool)(this["AutoDetermineBoostKingPet"]));
            }
            set {
                this["AutoDetermineBoostKingPet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForceBoostKingPet {
            get {
                return ((bool)(this["ForceBoostKingPet"]));
            }
            set {
                this["ForceBoostKingPet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseOldAssaCapture {
            get {
                return ((bool)(this["UseOldAssaCapture"]));
            }
            set {
                this["UseOldAssaCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" />")]
        public global::System.Collections.Specialized.StringCollection MapNameList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MapNameList"]));
            }
            set {
                this["MapNameList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>Lv1HP</string>
  <string>Tab</string>
  <string>Lv1Attack</string>
  <string>Tab</string>
  <string>Lv1Armor</string>
  <string>Tab</string>
  <string>Lv1Speed</string>
  <string>Tab</string>
  <string>Level</string>
  <string>Tab</string>
  <string>HP</string>
  <string>Tab</string>
  <string>Attack</string>
  <string>Tab</string>
  <string>Armor</string>
  <string>Tab</string>
  <string>Speed</string>
  <string>Tab</string>
  <string>HPRate</string>
  <string>Tab</string>
  <string>AttackRate</string>
  <string>Tab</string>
  <string>ArmorRate</string>
  <string>Tab</string>
  <string>SpeedRate</string>
  <string>Tab</string>
  <string>CombinedRate</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PetStatCopyFormat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PetStatCopyFormat"]));
            }
            set {
                this["PetStatCopyFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchAllProcesses {
            get {
                return ((bool)(this["SearchAllProcesses"]));
            }
            set {
                this["SearchAllProcesses"] = value;
            }
        }
    }
}
